export enum Locale {
  En = 'en',
  Ru = 'ru',
}

export enum AccountStatus {
  ACTIVE = 1,
  DISABLED = 2,
  UNSETTLED = 3,
  PENDING_RISK_REVIEW = 7,
  PENDING_SETTLEMENT = 8,
  IN_GRACE_PERIOD = 9,
  PENDING_CLOSURE = 100,
  CLOSED = 101,
  ANY_ACTIVE = 201,
  ANY_CLOSED = 202,
}

export enum AccountDisableReason {
  NONE = 0,
  ADS_INTEGRITY_POLICY = 1,
  ADS_IP_REVIEW = 2,
  RISK_PAYMENT = 3,
  GRAY_ACCOUNT_SHUT_DOWN = 4,
  ADS_AFC_REVIEW = 5,
  BUSINESS_INTEGRITY_RAR = 6,
  PERMANENT_CLOSE = 7,
  UNUSED_RESELLER_ACCOUNT = 8,
  UNUSED_ACCOUNT = 9,
}

export enum AdStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
}

export enum AdEffectiveStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  DELETED = 'DELETED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  DISAPPROVED = 'DISAPPROVED',
  PREAPPROVED = 'PREAPPROVED',
  PENDING_BILLING_INFO = 'PENDING_BILLING_INFO',
  CAMPAIGN_PAUSED = 'CAMPAIGN_PAUSED',
  ARCHIVED = 'ARCHIVED',
  ADSET_PAUSED = 'ADSET_PAUSED',
  IN_PROCESS = 'IN_PROCESS',
  WITH_ISSUES = 'WITH_ISSUES',
}

export enum ActionType {
  'app_custom_event.fb_mobile_achievement_unlocked' = 'Mobile App Feature Unlocks',
  'app_custom_event.fb_mobile_activate_app' = 'Mobile App Starts',
  'app_custom_event.fb_mobile_add_payment_info' = 'Mobile App Payment Details',
  'app_custom_event.fb_mobile_add_to_cart' = 'Mobile App Adds To Cart',
  'app_custom_event.fb_mobile_add_to_wishlist' = 'Mobile App Adds to Wishlist',
  'app_custom_event.fb_mobile_complete_registration' = 'Mobile App Registrations',
  'app_custom_event.fb_mobile_content_view' = 'Mobile App Content Views',
  'app_custom_event.fb_mobile_initiated_checkout' = 'Mobile App Checkouts',
  'app_custom_event.fb_mobile_level_achieved' = 'Mobile App Achievements',
  'app_custom_event.fb_mobile_purchase' = 'Mobile App Purchases',
  'app_custom_event.fb_mobile_rate' = 'Mobile App Ratings',
  'app_custom_event.fb_mobile_search' = 'Mobile App Searchs',
  'app_custom_event.fb_mobile_spent_credits' = 'Mobile App Credit Spends',
  'app_custom_event.fb_mobile_tutorial_completion' = 'Mobile App Tutorial Completions',
  'app_custom_event.other' = 'Other Mobile App Actions',
  'app_install' = 'App Installs',
  'app_use' = 'App Uses',
  'checkin' = 'Check-ins',
  'comment' = 'Post Comments',
  'credit_spent' = 'Credit Spends',
  'games.plays' = 'Game Plays',
  'landing_page_view' = 'Landing Page Views',
  'like' = 'Page Likes',
  'link_click' = 'Link Clicks',
  'mobile_app_install' = 'Mobile App Installs',
  'offsite_conversion.fb_pixel_add_payment_info' = 'Adds Payment Info',
  'offsite_conversion.fb_pixel_add_to_cart' = 'Adds To Cart',
  'offsite_conversion.fb_pixel_add_to_wishlist' = 'Adds To Wishlist',
  'offsite_conversion.fb_pixel_complete_registration' = 'Completed Registration',
  'offsite_conversion.fb_pixel_custom' = 'Custom pixel events defined by the advertiser',
  'offsite_conversion.fb_pixel_initiate_checkout' = 'Initiates Checkout',
  'offsite_conversion.fb_pixel_lead' = 'Leads',
  'offsite_conversion.fb_pixel_purchase' = 'Purchases',
  'offsite_conversion.fb_pixel_search' = 'Searchs',
  'offsite_conversion.fb_pixel_view_content' = 'Views Content',
  'onsite_conversion.flow_complete' = 'On-Facebook Workflow Completions',
  'onsite_conversion.messaging_block' = 'Blocked Messaging Conversations',
  'onsite_conversion.messaging_conversation_started_7d' = 'Messaging Conversations Started',
  'onsite_conversion.messaging_first_reply' = 'New Messaging Conversations',
  'onsite_conversion.post_save' = 'Post Saves',
  'onsite_conversion.purchase' = 'On-Facebook Purchases',
  'outbound_click' = 'Outbound Clicks',
  'photo_view' = 'Page Photo Views',
  'post' = 'Post Shares',
  'post_reaction' = 'Post Reactions',
  'rsvp' = 'Event Responses',
  'video_view' = '3-Second Video Views',
}
